"""Regressions for hardening round three.

Two defects an independent review reproduced against c760266.

The first is the one the previous round's compatibility shim did not actually
close: reading a historical payload is not the same as reproducing it. The
submission fingerprint is taken over the whole serialised JSON and replay
compares against the fingerprint recorded at the time, so a shim that parses
perfectly while renaming a key or adding a `null` breaks replay silently.

The fixtures below were generated by **running the predecessor commits**, not by
constructing them with the current model — that would put the current model on
both sides of the comparison and prove nothing. Each carries the fingerprint
that code actually produced.
"""

import json
from datetime import timedelta
from pathlib import Path
from uuid import uuid4

import pytest

from src.core.models import AgentRole
from src.orchestration.commander.decision import decide
from src.orchestration.commander.models import CommanderDisposition
from src.orchestration.commander.policy import COMMANDER_CONTROL_V1
from src.orchestration.workflow.models import (
    EvidenceSubmission,
    EvidenceType,
    SynthesisPayload,
    WorkflowFailure,
)
from tests.commander.conftest import (
    build_stack,
    inject_pre_trigger_evidence,
    inject_trigger,
    open_case,
    record,
)

FIXTURES = Path(__file__).parent / "fixtures"

# Every commit that has written one of these payloads, and the shape each wrote
# for the optional timestamp. `bb462b4` is listed because it is a known state,
# not because it is a distinct shape: it reproduces the two older ones exactly
# and its own new output is byte-identical to `094cad3`.
GENERATIONS = ("9515b49", "094cad3", "c760266", "bb462b4")
KINDS = ("anchor", "fuse")


def cases() -> list[tuple[str, str]]:
    """Every (generation, entry) pair the fixtures actually contain."""
    found = []
    for generation in GENERATIONS:
        payloads = json.loads((FIXTURES / f"evidence-{generation}.json").read_text())
        found.extend((generation, entry) for entry in sorted(payloads))
    return found


ALL_CASES = cases()
ANCHOR_CASES = [pair for pair in ALL_CASES if pair[1].startswith("anchor")]
FUSE_CASES = [pair for pair in ALL_CASES if pair[1].startswith("fuse")]

# The historical ANCHOR payloads reference their setup and trigger by these
# keys. Evidence ids are `uuid5` of the key, so a test that writes them
# reproduces the ids the fixtures already name — no reference rewriting.
HISTORICAL_SETUP_KEY = "historical-setup"
HISTORICAL_TRIGGER_KEY = "historical-trigger"

pytestmark = pytest.mark.usefixtures("worker_db")


def historical(generation: str, entry: str) -> tuple[str, str]:
    """The raw submission JSON a predecessor wrote, and the fingerprint it got.

    Produced by running that commit in a throwaway worktree, never by building
    it with the current model — which would put the current model on both sides
    of the comparison and prove nothing.
    """
    payload = json.loads((FIXTURES / f"evidence-{generation}.json").read_text())[entry]
    return payload["submission_raw"], payload["fingerprint"]


# ============================== 1: historical serialisation is a contract


@pytest.mark.parametrize(("generation", "entry"), ALL_CASES)
def test_a_historical_payload_reserialises_to_exactly_its_stored_bytes(generation, entry):
    """Byte identity, not merely successful parsing.

    Four shapes have been written for one optional timestamp, and they differ in
    ways a single nullable field cannot express — an explicitly stored `null` is
    not the same bytes as an absent key, though both mean the same thing.
    Renaming a key, moving it, or supplying or dropping a `null` each changes
    the JSON and therefore the fingerprint, while leaving the payload perfectly
    readable.
    """
    raw, _ = historical(generation, entry)
    parsed = EvidenceSubmission.model_validate_json(raw)
    assert parsed.model_dump_json() == raw


@pytest.mark.parametrize(("generation", "entry"), ALL_CASES)
def test_a_historical_payload_still_computes_its_original_fingerprint(generation, entry):
    """The comparison replay actually performs."""
    raw, original = historical(generation, entry)
    assert EvidenceSubmission.model_validate_json(raw).fingerprint() == original


@pytest.mark.parametrize(
    ("generation", "entry", "key", "has_value"),
    [
        ("9515b49", "fuse", "evaluated_at", True),
        ("094cad3", "fuse", None, False),
        ("c760266", "fuse", "legacy_evaluated_at", False),
        ("c760266", "fuse_with_value", "legacy_evaluated_at", True),
        ("bb462b4", "fuse", None, False),
        ("bb462b4", "fuse_with_value", "evaluated_at", True),
    ],
)
def test_each_generation_kept_its_own_shape(generation, entry, key, has_value):
    """The fixtures differ in exactly the ways the defects were about.

    Stated explicitly so the tests above cannot quietly become vacuous: an
    absent key, an explicit `null` and a carried value are three different
    things, and two different spellings have been used for the same field.
    """
    raw, _ = historical(generation, entry)
    detail = json.loads(raw)["payload"]["synthesis"]
    present = [name for name in ("evaluated_at", "legacy_evaluated_at") if name in detail]
    assert present == ([key] if key else [])
    if key:
        assert (detail[key] is not None) is has_value


def test_the_interim_shape_is_the_one_that_was_missing():
    """`c760266` wrote a spelling and a null nothing else did.

    It is also the only generation whose ANCHOR payload put the key *after*
    `execution_digest` rather than before it, so both the name and the position
    had to be remembered rather than inferred.
    """
    raw, _ = historical("c760266", "anchor")
    detail = json.loads(raw)["payload"]["execution"]
    assert list(detail)[-1] == "legacy_evaluated_at"
    assert detail["legacy_evaluated_at"] is None

    original, _ = historical("9515b49", "anchor")
    older = json.loads(original)["payload"]["execution"]
    assert list(older)[-2:] == ["evaluated_at", "execution_digest"]


def test_the_current_generation_introduced_no_new_shape():
    """`bb462b4` reproduces the older forms and writes `094cad3`'s exactly.

    Worth asserting rather than assuming: if it had invented a fifth shape,
    every row it wrote would need its own compatibility rule.
    """
    for entry, matching in (("fuse", "094cad3"), ("fuse_with_value", "9515b49")):
        current, current_fp = historical("bb462b4", entry)
        older, older_fp = historical(matching, "fuse")
        assert current == older
        assert current_fp == older_fp


DETAIL_FIELD = {"anchor": "execution", "fuse": "synthesis"}


def detail_of(raw: str, kind: str) -> dict:
    return json.loads(raw)["payload"][DETAIL_FIELD[kind]]


def timestamp_of(parsed: EvidenceSubmission, kind: str):
    return getattr(parsed.payload, DETAIL_FIELD[kind]).legacy_evaluated_at


@pytest.mark.parametrize("kind", KINDS)
def test_an_explicitly_stored_null_is_not_the_same_as_an_absent_key(kind):
    """Two ways of saying "no timestamp" that are not interchangeable.

    `094cad3` omitted the key; `c760266` wrote it with `null`. Both parse to the
    same `None`, so a model with one nullable field cannot tell them apart on the
    way back out — and the fingerprint is taken over the bytes, not the value.
    Collapsing them would make one of the two generations unreplayable.
    """
    absent_raw, absent_fp = historical("094cad3", kind)
    null_raw, null_fp = historical("c760266", kind)

    assert detail_of(absent_raw, kind).get("legacy_evaluated_at", "missing") == "missing"
    assert detail_of(null_raw, kind)["legacy_evaluated_at"] is None

    absent = EvidenceSubmission.model_validate_json(absent_raw)
    explicit = EvidenceSubmission.model_validate_json(null_raw)
    assert timestamp_of(absent, kind) is None
    assert timestamp_of(explicit, kind) is None

    assert absent.model_dump_json() == absent_raw
    assert explicit.model_dump_json() == null_raw
    assert absent_fp != null_fp, "identical meaning, different stored identity"


@pytest.mark.parametrize("kind", KINDS)
def test_one_value_under_two_spellings_keeps_two_identities(kind):
    """The same instant, written under two field names, is two fingerprints.

    `9515b49` called it `evaluated_at` and `c760266` called it
    `legacy_evaluated_at`. Reading both through one alias was the previous
    round's fix and is not enough: whichever spelling the writer used has to come
    back out, or that generation's stored fingerprint no longer matches.
    """
    older_raw, older_fp = historical("9515b49", kind)
    interim_raw, interim_fp = historical("c760266", f"{kind}_with_value")

    older = EvidenceSubmission.model_validate_json(older_raw)
    interim = EvidenceSubmission.model_validate_json(interim_raw)
    assert timestamp_of(older, kind) == timestamp_of(interim, kind) is not None

    assert "evaluated_at" in detail_of(older_raw, kind)
    assert "legacy_evaluated_at" in detail_of(interim_raw, kind)
    assert older.model_dump_json() == older_raw
    assert interim.model_dump_json() == interim_raw
    assert older_fp != interim_fp


@pytest.mark.parametrize(("generation", "entry"), FUSE_CASES)
async def test_a_historical_synthesis_replays_unchanged_through_the_real_service(
    worker_db, now, generation, entry
):
    """The end the previous round missed: replay through the workflow itself.

    Nothing about the submission is altered — not even its correlation, which is
    a binding to the case rather than content, so the case is opened under the
    fixture's own instead. The fingerprint the predecessor computed therefore
    survives all the way into the stored row, which is what replay compares
    against.
    """
    _, sessions = worker_db
    raw, original = historical(generation, entry)
    stored = EvidenceSubmission.model_validate_json(raw)
    assert stored.fingerprint() == original

    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(
        runtime.cases, now, stored.correlation_id, f"r3-replay-{generation}-{entry}"
    )

    first = await runtime.cases.record_evidence(trade_case.id, stored)
    replay = await runtime.cases.record_evidence(trade_case.id, stored)

    assert replay.evidence_id == first.evidence_id
    assert first.submission_fingerprint == original, "the stored identity is the original"
    synthesis = [
        item
        for item in await runtime.cases.evidence(trade_case.id)
        if item.evidence_type == EvidenceType.SYNTHESIS
    ]
    assert len(synthesis) == 1


@pytest.mark.parametrize(("generation", "entry"), ANCHOR_CASES)
async def test_a_historical_execution_assessment_replays_unchanged(
    worker_db, now, generation, entry
):
    """The same property for ANCHOR, whose payload the service cross-checks.

    Execution evidence names the setup and trigger it was assessed against, and
    the service refuses references that do not exist. An earlier version of this
    test rewrote those two ids to match a freshly built case — which quietly
    re-serialised the submission with the current model and destroyed the very
    fingerprint it was meant to prove.

    Nothing is rewritten now. Evidence ids are `uuid5` of the idempotency key, so
    the fixtures were generated naming the ids that `historical-setup` and
    `historical-trigger` produce, and the test writes exactly those keys. The
    historical envelope reaches the service byte for byte, including the legacy
    timestamp in whichever of its four shapes that generation wrote.
    """
    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    raw, original = historical(generation, entry)
    stored = EvidenceSubmission.model_validate_json(raw)
    assert stored.fingerprint() == original

    trade_case = await open_case(
        runtime.cases, now, stored.correlation_id, f"r3-anchor-{generation}-{entry}"
    )
    setup = await inject_pre_trigger_evidence(
        runtime.cases, trade_case, now, setup_key=HISTORICAL_SETUP_KEY
    )
    trigger = await inject_trigger(
        runtime.cases, trade_case, now, setup, key=HISTORICAL_TRIGGER_KEY
    )
    assert stored.payload.setup_evidence_id == setup.evidence_id, "no rebinding was needed"
    assert stored.payload.trigger_evidence_id == trigger.evidence_id

    first = await runtime.cases.record_evidence(trade_case.id, stored)
    replay = await runtime.cases.record_evidence(trade_case.id, stored)

    assert replay.evidence_id == first.evidence_id
    assert first.submission_fingerprint == original, "the stored identity is the original"
    execution = [
        item
        for item in await runtime.cases.evidence(trade_case.id)
        if item.evidence_type == EvidenceType.LIQUIDITY_EXECUTION
    ]
    assert len(execution) == 1


async def test_changed_content_under_the_same_key_is_still_a_conflict(worker_db, now):
    """The control. Compatibility must not weaken the conflict check."""
    _, sessions = worker_db
    raw, _ = historical("9515b49", "fuse")
    stored = EvidenceSubmission.model_validate_json(raw)

    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, stored.correlation_id, "r3-conflict")
    await runtime.cases.record_evidence(trade_case.id, stored)

    altered = stored.model_copy(update={"reason_codes": ("CHANGED",)})
    assert altered.fingerprint() != stored.fingerprint()
    with pytest.raises(WorkflowFailure):
        await runtime.cases.record_evidence(trade_case.id, altered)


@pytest.mark.parametrize("generation", GENERATIONS)
@pytest.mark.parametrize("kind", KINDS)
def test_unknown_fields_are_still_refused(generation, kind):
    """No blanket field ignoring: a typo must fail rather than vanish."""
    raw, _ = historical(generation, kind)
    payload = json.loads(raw)
    key = "execution" if kind == "anchor" else "synthesis"
    payload["payload"][key]["polcy_version"] = "typo"
    with pytest.raises(ValueError):
        EvidenceSubmission.model_validate(payload)


async def test_new_computations_carry_no_timestamp_and_stay_idempotent(worker_db, now, trace):
    """New work remains free of run metadata, whatever the compatibility shim does."""
    from tests.commander.test_hardening import _synthesize

    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-new-idempotent")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)

    first = await _synthesize(runtime, trade_case, now, trace)
    second = await _synthesize(runtime, trade_case, now + timedelta(seconds=5), trace)

    assert first.fingerprint() == second.fingerprint()
    assert first.payload.synthesis.legacy_evaluated_at is None
    assert "evaluated_at" not in json.loads(first.model_dump_json())["payload"]["synthesis"]


# ==================== 2: advisory evidence does not age the decision window


@pytest.mark.parametrize(
    "synthesis_validity",
    # A submission may not be written already expired, so the expired-at-decision
    # case is the short one evaluated past its own validity below.
    [timedelta(minutes=1), timedelta(minutes=2), timedelta(hours=4)],
    ids=["much-shorter", "shorter", "longer"],
)
async def test_an_advisory_synthesis_never_moves_the_decision_window(
    worker_db, now, trace, synthesis_validity
):
    """Identical canonical evidence must give an identical window, every time.

    Compared within one case, before and after the synthesis is recorded, so the
    only thing that differs is the advisory envelope. An advisory synthesis is
    authoritative over nothing; letting its envelope age the view would hand the
    advisory layer a way to force re-derivation of decisions it has no say in —
    the same authority it is kept out of the context digest to deny it.
    """
    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, f"r3-window-{synthesis_validity}")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)

    before = await reader.commander_context(trade_case.id, uuid4())

    await record(
        runtime.cases,
        trade_case,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key=f"r3-window-synthesis-{synthesis_validity}",
        valid_until=now + synthesis_validity,
    )
    after = await reader.commander_context(trade_case.id, uuid4())

    assert after.valid_until == before.valid_until
    assert after.context_digest == before.context_digest

    # Past the synthesis's own validity, both still decide the same thing.
    beyond = now + timedelta(minutes=3)
    assert decide(after, beyond, COMMANDER_CONTROL_V1).disposition == (
        decide(before, beyond, COMMANDER_CONTROL_V1).disposition
    )
    assert decide(after, beyond, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.AWAIT_TRIGGER
    )


async def test_an_absent_synthesis_gives_the_same_window_as_a_present_one(worker_db, now, trace):
    """The other direction: recording one changes nothing, so absence matches."""
    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)

    without = await open_case(runtime.cases, now, trace, "r3-window-without")
    await inject_pre_trigger_evidence(runtime.cases, without, now)
    plain = await reader.commander_context(without.id, uuid4())

    with_fuse = await open_case(runtime.cases, now, trace, "r3-window-with")
    await inject_pre_trigger_evidence(runtime.cases, with_fuse, now)
    await record(
        runtime.cases,
        with_fuse,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key="r3-window-with-synthesis",
        valid_until=now + timedelta(minutes=2),
    )
    advised = await reader.commander_context(with_fuse.id, uuid4())

    # Different cases, so the digests differ by identity; the window must not.
    assert advised.valid_until == plain.valid_until
    beyond = now + timedelta(minutes=3)
    assert decide(advised, beyond, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.AWAIT_TRIGGER
    )


async def test_advisory_freshness_is_still_reported_separately(worker_db, now, trace):
    """Excluded from the window, not from the view: staleness is still visible."""
    from tests.commander.test_hardening import _record_synthesis

    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-advisory-visible")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)
    submission = await _record_synthesis(sessions, runtime, trade_case, now, trace)

    beyond = submission.valid_until + timedelta(minutes=1)
    _, late_reader = build_stack(sessions, beyond)
    context = await late_reader.commander_context(trade_case.id, uuid4())

    assert context.advisory is not None
    assert context.advisory.expired is True
    assert context.advisory.is_usable is False


async def test_canonical_horizons_still_bound_the_window_exactly(worker_db, now, trace):
    """§2's other half: removing FUSE must not loosen anything else.

    The setup's own expiry is the tightest horizon here, and it still decides
    the boundary to the microsecond.
    """
    from tests.fuse.conftest import trade_setup

    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-canonical-bound")
    await inject_pre_trigger_evidence(
        runtime.cases,
        trade_case,
        now,
        trade_setup=trade_setup(now, expires_in=timedelta(minutes=4)),
    )
    await record(
        runtime.cases,
        trade_case,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key="r3-canonical-synthesis",
        valid_until=now + timedelta(minutes=1),
    )
    context = await reader.commander_context(trade_case.id, uuid4())

    boundary = now + timedelta(minutes=4)
    assert context.valid_until == boundary
    assert (
        decide(context, boundary - timedelta(microseconds=1), COMMANDER_CONTROL_V1).disposition
        == CommanderDisposition.AWAIT_TRIGGER
    )
    assert decide(context, boundary, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.STALE_CONTEXT
    )
