"""Regressions for hardening round three.

Two defects an independent review reproduced against c760266.

The first is the one the previous round's compatibility shim did not actually
close: reading a historical payload is not the same as reproducing it. The
submission fingerprint is taken over the whole serialised JSON and replay
compares against the fingerprint recorded at the time, so a shim that parses
perfectly while renaming a key or adding a `null` breaks replay silently.

The fixtures below were generated by **running the predecessor commits**, not by
constructing them with the current model — that would put the current model on
both sides of the comparison and prove nothing. Each carries the fingerprint
that code actually produced.
"""

import json
from datetime import timedelta
from pathlib import Path
from uuid import uuid4

import pytest

from src.core.models import AgentRole
from src.orchestration.commander.decision import decide
from src.orchestration.commander.models import CommanderDisposition
from src.orchestration.commander.policy import COMMANDER_CONTROL_V1
from src.orchestration.workflow.models import (
    EvidenceSubmission,
    EvidenceType,
    SynthesisPayload,
    WorkflowFailure,
)
from tests.commander.conftest import (
    build_stack,
    inject_pre_trigger_evidence,
    open_case,
    record,
)

FIXTURES = Path(__file__).parent / "fixtures"
GENERATIONS = ("9515b49", "094cad3")
KINDS = ("anchor", "fuse")

pytestmark = pytest.mark.usefixtures("worker_db")


def historical(generation: str, kind: str) -> tuple[str, str]:
    """The raw submission JSON a predecessor wrote, and the fingerprint it got."""
    entry = json.loads((FIXTURES / f"evidence-{generation}.json").read_text())[kind]
    return entry["submission_raw"], entry["fingerprint"]


# ============================== 1: historical serialisation is a contract


@pytest.mark.parametrize("generation", GENERATIONS)
@pytest.mark.parametrize("kind", KINDS)
def test_a_historical_payload_reserialises_to_exactly_its_stored_bytes(generation, kind):
    """Byte identity, not merely successful parsing.

    `9515b49` wrote an `evaluated_at` key; `094cad3` wrote no such key at all.
    Renaming the first or adding a `null` for the second each changes the JSON
    and therefore the fingerprint, while leaving the payload perfectly readable.
    """
    raw, _ = historical(generation, kind)
    parsed = EvidenceSubmission.model_validate_json(raw)
    assert parsed.model_dump_json() == raw


@pytest.mark.parametrize("generation", GENERATIONS)
@pytest.mark.parametrize("kind", KINDS)
def test_a_historical_payload_still_computes_its_original_fingerprint(generation, kind):
    """The comparison replay actually performs."""
    raw, original = historical(generation, kind)
    assert EvidenceSubmission.model_validate_json(raw).fingerprint() == original


@pytest.mark.parametrize("generation", GENERATIONS)
def test_the_two_generations_kept_their_different_shapes(generation):
    """The fixtures differ in the way the defect was about, so the tests bite."""
    raw, _ = historical(generation, "fuse")
    detail = json.loads(raw)["payload"]["synthesis"]
    if generation == "9515b49":
        assert "evaluated_at" in detail
        assert detail["evaluated_at"] is not None
    else:
        assert "evaluated_at" not in detail
    assert "legacy_evaluated_at" not in detail


@pytest.mark.parametrize("generation", GENERATIONS)
async def test_a_historical_synthesis_replays_unchanged_through_the_real_service(
    worker_db, now, generation
):
    """The end the previous round missed: replay through the workflow itself.

    Nothing about the submission is altered — not even its correlation, which is
    a binding to the case rather than content, so the case is opened under the
    fixture's own instead. The fingerprint the predecessor computed therefore
    survives all the way into the stored row, which is what replay compares
    against.
    """
    _, sessions = worker_db
    raw, original = historical(generation, "fuse")
    stored = EvidenceSubmission.model_validate_json(raw)
    assert stored.fingerprint() == original

    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(
        runtime.cases, now, stored.correlation_id, f"r3-replay-{generation}"
    )

    first = await runtime.cases.record_evidence(trade_case.id, stored)
    replay = await runtime.cases.record_evidence(trade_case.id, stored)

    assert replay.evidence_id == first.evidence_id
    assert first.submission_fingerprint == original, "the stored identity is the original"
    synthesis = [
        item
        for item in await runtime.cases.evidence(trade_case.id)
        if item.evidence_type == EvidenceType.SYNTHESIS
    ]
    assert len(synthesis) == 1


@pytest.mark.parametrize("generation", GENERATIONS)
async def test_a_historical_execution_assessment_replays_through_the_real_service(
    worker_db, now, generation
):
    """The same property for ANCHOR, whose payload the service cross-checks.

    Execution evidence names the setup and trigger it was assessed against, and
    the service refuses references that do not exist — so those two ids are
    rebound to a real case here. Everything else, including the legacy
    timestamp's presence or absence, is exactly as the predecessor wrote it, and
    the round trip through the model is what the replay comparison rests on.
    """
    from src.orchestration.workflow.engine import active_evidence
    from tests.commander.conftest import inject_trigger

    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    raw, _ = historical(generation, "anchor")
    parsed = EvidenceSubmission.model_validate_json(raw)
    trade_case = await open_case(
        runtime.cases, now, parsed.correlation_id, f"r3-anchor-{generation}"
    )
    setup = await inject_pre_trigger_evidence(runtime.cases, trade_case, now)
    await inject_trigger(runtime.cases, trade_case, now, setup)
    current = active_evidence(await runtime.cases.evidence(trade_case.id))

    rebound = parsed.model_copy(
        update={
            "payload": parsed.payload.model_copy(
                update={
                    "setup_evidence_id": setup.evidence_id,
                    "trigger_evidence_id": current[EvidenceType.TRIGGER].evidence_id,
                }
            ),
        }
    )
    # The legacy shape survived the copy: that is what replay depends on.
    detail = json.loads(rebound.model_dump_json())["payload"]["execution"]
    assert ("evaluated_at" in detail) == (generation == "9515b49")
    assert "legacy_evaluated_at" not in detail

    first = await runtime.cases.record_evidence(trade_case.id, rebound)
    replay = await runtime.cases.record_evidence(trade_case.id, rebound)

    assert replay.evidence_id == first.evidence_id
    assert first.submission_fingerprint == rebound.fingerprint()
    execution = [
        item
        for item in await runtime.cases.evidence(trade_case.id)
        if item.evidence_type == EvidenceType.LIQUIDITY_EXECUTION
    ]
    assert len(execution) == 1


async def test_changed_content_under_the_same_key_is_still_a_conflict(worker_db, now):
    """The control. Compatibility must not weaken the conflict check."""
    _, sessions = worker_db
    raw, _ = historical("9515b49", "fuse")
    stored = EvidenceSubmission.model_validate_json(raw)

    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, stored.correlation_id, "r3-conflict")
    await runtime.cases.record_evidence(trade_case.id, stored)

    altered = stored.model_copy(update={"reason_codes": ("CHANGED",)})
    assert altered.fingerprint() != stored.fingerprint()
    with pytest.raises(WorkflowFailure):
        await runtime.cases.record_evidence(trade_case.id, altered)


@pytest.mark.parametrize("generation", GENERATIONS)
@pytest.mark.parametrize("kind", KINDS)
def test_unknown_fields_are_still_refused(generation, kind):
    """No blanket field ignoring: a typo must fail rather than vanish."""
    raw, _ = historical(generation, kind)
    payload = json.loads(raw)
    key = "execution" if kind == "anchor" else "synthesis"
    payload["payload"][key]["polcy_version"] = "typo"
    with pytest.raises(ValueError):
        EvidenceSubmission.model_validate(payload)


async def test_new_computations_carry_no_timestamp_and_stay_idempotent(worker_db, now, trace):
    """New work remains free of run metadata, whatever the compatibility shim does."""
    from tests.commander.test_hardening import _synthesize

    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-new-idempotent")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)

    first = await _synthesize(runtime, trade_case, now, trace)
    second = await _synthesize(runtime, trade_case, now + timedelta(seconds=5), trace)

    assert first.fingerprint() == second.fingerprint()
    assert first.payload.synthesis.legacy_evaluated_at is None
    assert "evaluated_at" not in json.loads(first.model_dump_json())["payload"]["synthesis"]


# ==================== 2: advisory evidence does not age the decision window


@pytest.mark.parametrize(
    "synthesis_validity",
    # A submission may not be written already expired, so the expired-at-decision
    # case is the short one evaluated past its own validity below.
    [timedelta(minutes=1), timedelta(minutes=2), timedelta(hours=4)],
    ids=["much-shorter", "shorter", "longer"],
)
async def test_an_advisory_synthesis_never_moves_the_decision_window(
    worker_db, now, trace, synthesis_validity
):
    """Identical canonical evidence must give an identical window, every time.

    Compared within one case, before and after the synthesis is recorded, so the
    only thing that differs is the advisory envelope. An advisory synthesis is
    authoritative over nothing; letting its envelope age the view would hand the
    advisory layer a way to force re-derivation of decisions it has no say in —
    the same authority it is kept out of the context digest to deny it.
    """
    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, f"r3-window-{synthesis_validity}")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)

    before = await reader.commander_context(trade_case.id, uuid4())

    await record(
        runtime.cases,
        trade_case,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key=f"r3-window-synthesis-{synthesis_validity}",
        valid_until=now + synthesis_validity,
    )
    after = await reader.commander_context(trade_case.id, uuid4())

    assert after.valid_until == before.valid_until
    assert after.context_digest == before.context_digest

    # Past the synthesis's own validity, both still decide the same thing.
    beyond = now + timedelta(minutes=3)
    assert decide(after, beyond, COMMANDER_CONTROL_V1).disposition == (
        decide(before, beyond, COMMANDER_CONTROL_V1).disposition
    )
    assert decide(after, beyond, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.AWAIT_TRIGGER
    )


async def test_an_absent_synthesis_gives_the_same_window_as_a_present_one(worker_db, now, trace):
    """The other direction: recording one changes nothing, so absence matches."""
    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)

    without = await open_case(runtime.cases, now, trace, "r3-window-without")
    await inject_pre_trigger_evidence(runtime.cases, without, now)
    plain = await reader.commander_context(without.id, uuid4())

    with_fuse = await open_case(runtime.cases, now, trace, "r3-window-with")
    await inject_pre_trigger_evidence(runtime.cases, with_fuse, now)
    await record(
        runtime.cases,
        with_fuse,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key="r3-window-with-synthesis",
        valid_until=now + timedelta(minutes=2),
    )
    advised = await reader.commander_context(with_fuse.id, uuid4())

    # Different cases, so the digests differ by identity; the window must not.
    assert advised.valid_until == plain.valid_until
    beyond = now + timedelta(minutes=3)
    assert decide(advised, beyond, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.AWAIT_TRIGGER
    )


async def test_advisory_freshness_is_still_reported_separately(worker_db, now, trace):
    """Excluded from the window, not from the view: staleness is still visible."""
    from tests.commander.test_hardening import _record_synthesis

    _, sessions = worker_db
    runtime, _ = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-advisory-visible")
    await inject_pre_trigger_evidence(runtime.cases, trade_case, now)
    submission = await _record_synthesis(sessions, runtime, trade_case, now, trace)

    beyond = submission.valid_until + timedelta(minutes=1)
    _, late_reader = build_stack(sessions, beyond)
    context = await late_reader.commander_context(trade_case.id, uuid4())

    assert context.advisory is not None
    assert context.advisory.expired is True
    assert context.advisory.is_usable is False


async def test_canonical_horizons_still_bound_the_window_exactly(worker_db, now, trace):
    """§2's other half: removing FUSE must not loosen anything else.

    The setup's own expiry is the tightest horizon here, and it still decides
    the boundary to the microsecond.
    """
    from tests.fuse.conftest import trade_setup

    _, sessions = worker_db
    runtime, reader = build_stack(sessions, now)
    trade_case = await open_case(runtime.cases, now, trace, "r3-canonical-bound")
    await inject_pre_trigger_evidence(
        runtime.cases,
        trade_case,
        now,
        trade_setup=trade_setup(now, expires_in=timedelta(minutes=4)),
    )
    await record(
        runtime.cases,
        trade_case,
        now,
        AgentRole.FUSE,
        EvidenceType.SYNTHESIS,
        SynthesisPayload(disposition="COHERENT", source_evidence_ids=(uuid4(),)),
        key="r3-canonical-synthesis",
        valid_until=now + timedelta(minutes=1),
    )
    context = await reader.commander_context(trade_case.id, uuid4())

    boundary = now + timedelta(minutes=4)
    assert context.valid_until == boundary
    assert (
        decide(context, boundary - timedelta(microseconds=1), COMMANDER_CONTROL_V1).disposition
        == CommanderDisposition.AWAIT_TRIGGER
    )
    assert decide(context, boundary, COMMANDER_CONTROL_V1).disposition == (
        CommanderDisposition.STALE_CONTEXT
    )
